### ISSUE TITLE
What's the benefit this library bring to react?

### ISSUE THREAD

**Issue by adamchenwei** [leebyron/react-loops#8]
Is this just syntax sugar for loop? Lol I never thought React Dev favor a angularjs and Vue ish syntax, which I would run far away from because it's adding unnecessary syntax sugar above .map which is completely easy to understand as it's just JS!

sorry I am just not buying it lol but maybe someone will enjoy it? Then may as well go to code with Vue or angularjs lol

**Comment by joglr** [comment]
I can't really see the pros of this library either.

**Comment by gretzky** [comment]
JS has come so full circle that I can't figure out if this is an April Fools thing or not

**Comment by gretzky** [comment]
Haha, JS has come so full circle that this genuinely could or could not be an April Fools joke

**Comment by ryansolid** [comment]
The only benefit I see with this is if like Hooks this tests people's comfort with APIs you would find with Fine Grained architectures. It would be fairly straightforward to take something like this and Hooks and bypass using the Virtual DOM at all if desired. Not suggesting React would head that way but it's interesting.

I suspect this is a joke but this "Velcro Architecture" API is reminiscent to one of the fastest libraries(Solid) in the [JS Frameworks Benchmark](https://github.com/krausest/js-framework-benchmark), so you never know.

**Comment by leebyron** [comment]
The benefit is much clearer syntax for including collections of values in a React tree. This is a pattern I see in nearly every React app I encounter. It also addresses a pain-point many feel when first learning React, where it is not clear how to follow this pattern.

Eventually you learn about using the `map()` operator, but even then you must be careful to remember to use `key=` properly. If you need to include a collection that is not an Array and does not have `map()` then it's not always clear how to proceed. The ES6 `Map` and `Set` collections are great examples, and they're under-used by React projects because of this incidental complexity. Using `Object` as a collection is also a common JS paradigm but notoriously annoying to use as a collection. Nearly half the API of lodash addresses this fact. Using `Object.keys()` is not always clear to new-comers and `Object.values()` and `Object.entries()` still have browser compatibility issues and now we're talking polyfills.

Seriously! Looping over collections in Javascript is _possible_ but harder than it should be!

I would not suggest snubbing your nose at this idea because it's too much like Angular or Vue. Smart people built those libraries and smart people use them. Yes, React Loops was inspired by Angular and Vue, which were themselves inspired by XSLT, JSTL, and E4X. I wouldn't suggest anyone go build something new with JSTL over React, but I also wouldn't suggest that we also abandon all aspects of these ideas.

My specific criticism of Angular and Vue directives as control flow is not that they replace existing JS methods, it's that they affect _scope_ in ways that are difficult to understand (and test) and that they are attributes (props) that can be placed _on any node_ which makes them difficult to type-check.

React Loops tries to keep the good parts of describing looping control flow as part of a JSX template, while avoiding the issues I see with Angular style directives. Perhaps interesting is that I think the much older JSTL and XSLT patterns got this closer to right by having control flow be their own nodes in the tree. That both allows for correct type-checking and clarifies scoping. React Loops goes further by using arrow functions (or even render props) so that plain ol' Javascript variable scope still applies - in that way it's still "Just Javascript." In contrast, Angular and Vue require compilers beyond the simpler JSX transform (in fact React Loops, like other React components, can work without JSX by using `React.createElement()`)
